[build]
  functions = "netlify/functions"
  publish = "."

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "FROM_EMAIL,SITE_URL"

[functions]
  node_bundler = "esbuild"

[functions."stripe-webhook"]
  included_files = []
